In [5]:
%pip install tensorflow

  Using cached tensorflow-2.9.1-cp310-cp310-win_amd64.whl (444.1 MB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached protobuf-3.19.4-cp310-cp310-win_amd64.whl (895 kB)
  Using cached tensorboard-2.9.1-py3-none-any.whl (5.8 MB)
  Using cached h5py-3.7.0-cp310-cp310-win_amd64.whl (2.6 MB)
  Using cached absl_py-1.2.0-py3-none-any.whl (123 kB)
  Using cached tensorflow_estimator-2.9.0-py2.py3-none-any.whl (438 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
  Using cached tensorflow_io_gcs_filesystem-0.26.0-cp310-cp310-win_amd64.whl (1.5 MB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
  Using cached grpcio-1.47.0-cp310-cp310-win_amd64.whl (3.5 MB)
  Using cached google_auth-2.10.0-py2.py3-none-any.whl (167 kB)
  Using cached google_auth_oauthlib-0.4.6

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\tensorflow_estimator\\python\\estimator\\inputs\\numpy_io.py'
Consider using the `--user` option or check the permissions.

You should consider upgrading via the 'c:\Users\hp\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [18]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [19]:
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values
print(X)


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() #encoding gender column
X[:,2] = le.fit_transform(X[:,2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
#passthrough means that any columns not encoded will not be removed
X = np.array(ct.fit_transform(X))   #encoding country column
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [24]:
#initalize ann
ann = tf.keras.models.Sequential()

In [25]:
#Add input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))    #Dense(No of neurons,Activation func)

In [26]:
#adding 2nd hidden layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu')) 

In [27]:
#add output layer
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid')) 
#sigmoid activation function for the output layer

In [28]:
#compile ann
ann.compile(optimizer ='adam' , loss ='binary_crossentropy' , metrics = ['accuracy'])

In [29]:
#training
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 3s 748us/step - loss: 0.5476 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 0s 680us/step - loss: 0.4705 - accuracy: 0.7974
Epoch 3/100
250/250 [==============================] - 0s 698us/step - loss: 0.4425 - accuracy: 0.8044
Epoch 4/100
250/250 [==============================] - 0s 706us/step - loss: 0.4277 - accuracy: 0.8081
Epoch 5/100
250/250 [==============================] - 0s 664us/step - loss: 0.4165 - accuracy: 0.8127
Epoch 6/100
250/250 [==============================] - 0s 668us/step - loss: 0.4077 - accuracy: 0.8170
Epoch 7/100
250/250 [==============================] - 0s 666us/step - loss: 0.4003 - accuracy: 0.8200
Epoch 8/100
250/250 [==============================] - 0s 651us/step - loss: 0.3940 - accuracy: 0.8225
Epoch 9/100
250/250 [==============================] - 0s 650us/step - loss: 0.3889 - accuracy: 0.8254
Epoch 10/100
250/250 [==============================] - 0s 689us/step - l

In [30]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 2s 604us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [31]:
#drawing the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1515   80]
 [ 191  214]]


0.8645